### ISSUE TITLE
Adding Xiaomi TH Sensor 2 (LYWSD03MMC) with CFW atc1441 or pvvx in HA

### ISSUE THREAD

**Issue by cgernert** [AlexxIT/gw3#4]
How to add Xiaomi TH Sensor 2 (LYWSD03MMC) with CFW atc1441 or pvvx in Home Assistant?
Sensors with CFW atc1441 or pvvx do not support MiHome app any more. 
After flashing CFW on sensors, the default advertising type is "custom" (ESP-like).
As I understand, the gw3 binary should map any BLE device to MQTT (mosquitto). 

... So the custom BLE devices should be discovered by Xiaomi Gateway 3 or MQTT integration in Home Assistant?
I am using modified v1.5.0_0102 hub firmware.

**Comment by AlexxIT** [comment]
https://github.com/custom-components/ble_monitor
